import Head from "next/head";
import About from "../Components/About";
import Features from "../Components/Features";
import Navbar from "../Components/Navbar";
import Testimonial from "../Components/Testimonial";
import { supabase } from "../utils/supabaseClient";
import { useState, useEffect } from "react";
import Feed from "../Components/Feed";
import Router from "next/router";

export default function Home() {
  const [session, setSession] = useState(null);
  useEffect(() => {
    async function getInitialSession() {
      const { data, error } = await supabase.auth.getSession();
      if (error) {
        console.log(error);
      } else {
        setSession(data);
        if (data && data.session)
          Router.push({
            pathname: "/feed",
          });
        console.log(data);
      }
    }
    getInitialSession();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {!session || session.session == null ? (
        <div>
          <Navbar isLogin={false}></Navbar>
          <About></About>
          <Features></Features>
          <Testimonial></Testimonial>
        </div>
      ) : (
        <div>Hello</div>
      )}
    </div>
  );
}
